apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: postgres:5432
    user: grafana
    editable: false
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      maxOpenConns: 2
      maxIdleConns: 2
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
