global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: follow-api
    static_configs:
      - targets: ["follow-api:8080"]
    metrics_path: /metrics

  - job_name: follow-image-gateway
    static_configs:
      - targets: ["follow-image-gateway:8090"]
    metrics_path: /metrics
