apiVersion: 1

contactPoints:
  - orgId: 1
    name: follow-email
    receivers:
      - uid: follow-email-receiver
        type: email
        sendResolved: true
        settings:
          addresses: yoseforb@gmail.com
          singleEmail: true
          subject: '{{ template "follow.subject" . }}'
          message: '{{ template "follow.message" . }}'
