apiVersion: 1

policies:
  - orgId: 1
    receiver: follow-telegram
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: follow-telegram
        matchers:
          - severity = critical
        group_by:
          - grafana_folder
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
        continue: true
      - receiver: follow-email
        matchers:
          - severity = critical
        group_by:
          - grafana_folder
        group_wait: 1m
        group_interval: 5m
        repeat_interval: 4h
        continue: false
